global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "streamlit_dashboard"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8003"]

  - job_name: rabbitmq-exporter
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]

  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: minio-bucket
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
      - targets: ["minio:9000"]

  - job_name: minio-resource
    metrics_path: /minio/v2/metrics/resource
    static_configs:
      - targets: ["minio:9000"]

  # These three will work AFTER we add /metrics servers in code
  - job_name: extractor
    static_configs:
      - targets: ["extractor:2112"]

  - job_name: transformer
    static_configs:
      - targets: ["transformer:8000"]

  - job_name: cleaner
    static_configs:
      - targets: ["cleaner:8000"]
